[package]
name = "cargo-v5"
version = "0.6.2"
edition = "2021"
authors = [
    "vexide",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
    "Tropical"
]
license = "MIT"
description = "A cargo subcommand for managing V5 Brain Rust projects"
repository = "https://github.com/vexide/cargo-pros"

[package.metadata.v5]
icon = "robot"
slot = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-subcommand-metadata = "0.1.0"
cargo_metadata = "0.18.0"
clap = { version = "4.4.2", features = ["derive"], optional = true }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.106"
fs-err = { version = "2.9.0", features = ["tokio"] }
cfg-if = "1.0.0"
inquire = "0.7.5"
indicatif = "0.17.8"
vex-v5-serial = { version = "0.2.0", default-features = false, features = ["serial"] }
tokio = { version = "1.23.0", features = ["full"] }
miette = { version = "7.2.0", features = ["fancy"] }
thiserror = "1.0.61"
object = { version = "0.36.1", default-features = false, features = ["std", "read_core", "elf"] }

[features]
default = ["clap"]
clap = ["dep:clap"]

[[bin]]
name = "cargo-v5"
required-features = ["clap"]
