[package]
name = "cargo-v5"
version = "0.6.0"
edition = "2021"
authors = [
    "vexide",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
]
license = "MIT"
description = "A cargo subcommand for managing vexide projects"
repository = "https://github.com/vexide/cargo-pros"

[package.metadata.v5.program]
icon = "cool-x"
slot = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-subcommand-metadata = "0.1.0"
cargo_metadata = "0.18.0"
cfg-if = "1.0.0"
fs-err = "2.9.0"
home = "0.5.5"
serde_json = "1.0.106"
clap = { version = "4.4.2", features = ["derive"], optional = true }
directories = "5.0.1"
toml = "0.8.14"
serde = { version = "1.0.203", features = ["derive"] }
anyhow = "1.0.86"
inquire = "0.7.5"
clap-cargo = { version = "0.14.0", features = ["clap", "cargo_metadata"] }

[features]
default = ["clap"]
clap = ["dep:clap"]

[[bin]]
name = "cargo-v5"
required-features = ["clap"]
